apiVersion: v1
kind: Pod
metadata: 
  name: nodeapp
  labels:
    app: nodeapp
# Creating container in Kubernetes    
spec:
  containers:
    - name: jenkins
      image: kammana/nodeapp:v1
      ports:
        - containerPort: 8080
